application: tara-cafe
version: 0-1-3
runtime: python
api_version: 1

builtins:
- appstats: on
- admin_redirect: on
- datastore_admin: on
- remote_api: on
- default: on
- mapreduce: on

handlers:
- url: /js
  static_dir: js
- url: /login(/.*|$)
  script: login.py
- url: /_ah/login_required
  script: login.py
- url: /tasks/.*
  script: tasks.py
  login: admin
- url: /room/.*
  script: room.py
- url: /[^/]*
  script: index.py
