application: tara-cafe
version: 0-1-1
runtime: python
api_version: 1

handlers:
- url: /js
  static_dir: js
- url: /login(/.*|$)
  script: login.py
- url: /tasks/.*
  script: tasks.py
  login: admin
- url: /room/.*
  script: room.py
- url: /.*
  script: index.py
